[package]
name = "dopplerfix"
version = "0.2.0"
edition = "2021"
build = "build.rs"


[dependencies]
byteorder = "1.4.3"
num = "0.4.0"
libc = "0.2.132"
clap = { version = "3.2.20", features = ["derive", "cargo"] }
regex = "1.6.0"
lazy_static = "1.4.0"
chrono = "0.4.22"

