[package]
name = "dopplerfix"
version = "0.1.1"
edition = "2021"
build = "build.rs"


[dependencies]
byteorder = "1.4.3"
num = "0.4.0"
libc = "0.2.132"
clap = { version = "3.1.18", features = ["derive"] }

